import { Token } from "../tokens";

// prettier-ignore
export const firstChar = [
  /*   0 -   */ Token.Unknown,
  /*   1 -   */ Token.Unknown,
  /*   2 -   */ Token.Unknown,
  /*   3 -   */ Token.Unknown,
  /*   4 -   */ Token.Unknown,
  /*   5 -   */ Token.Unknown,
  /*   6 -   */ Token.Unknown,
  /*   7 -   */ Token.Unknown,
  /*   8 -   */ Token.Unknown,
  /*   9 -   */ Token.Unknown,
  /*  10 -   */ Token.Unknown,
  /*  11 -   */ Token.Unknown,
  /*  12 -   */ Token.Unknown,
  /*  13 -   */ Token.Unknown,
  /*  14 -   */ Token.Unknown,
  /*  15 -   */ Token.Unknown,
  /*  16 -   */ Token.Unknown,
  /*  17 -   */ Token.Unknown,
  /*  18 -   */ Token.Unknown,
  /*  19 -   */ Token.Unknown,
  /*  20 -   */ Token.Unknown,
  /*  21 -   */ Token.Unknown,
  /*  22 -   */ Token.Unknown,
  /*  23 -   */ Token.Unknown,
  /*  24 -   */ Token.Unknown,
  /*  25 -   */ Token.Unknown,
  /*  26 -   */ Token.Unknown,
  /*  27 -   */ Token.Unknown,
  /*  28 -   */ Token.Unknown,
  /*  29 -   */ Token.Unknown,
  /*  30 -   */ Token.Unknown,
  /*  31 -   */ Token.Unknown,
  /*  32 -   */ Token.Unknown,
  /*  33 - ! */ Token.Unknown, // FIXME,
  /*  34 - " */ Token.StringLiteral,
  /*  35 - # */ Token.Unknown,
  /*  36 - $ */ Token.Identifier,
  /*  37 - % */ Token.Unknown,
  /*  38 - & */ Token.Unknown,
  /*  39 - ' */ Token.StringLiteral,
  /*  40 - ( */ Token.OpenParen,
  /*  41 - ) */ Token.CloseParen,
  /*  42 - * */ Token.Unknown,
  /*  43 - + */ Token.Unknown,
  /*  44 - , */ Token.Comma,
  /*  45 - - */ Token.Unknown,
  /*  46 - . */ Token.Unknown,
  /*  47 - / */ Token.Unknown,
  /*  48 - 0 */ Token.NumericLiteral,
  /*  49 - 1 */ Token.NumericLiteral,
  /*  50 - 2 */ Token.NumericLiteral,
  /*  51 - 3 */ Token.NumericLiteral,
  /*  52 - 4 */ Token.NumericLiteral,
  /*  53 - 5 */ Token.NumericLiteral,
  /*  54 - 6 */ Token.NumericLiteral,
  /*  55 - 7 */ Token.NumericLiteral,
  /*  56 - 8 */ Token.NumericLiteral,
  /*  57 - 9 */ Token.NumericLiteral,
  /*  58 - : */ Token.Colon,
  /*  59 - ; */ Token.SemiColon,
  /*  60 - < */ Token.Unknown,
  /*  61 - = */ Token["="],
  /*  62 - > */ Token.Unknown,
  /*  63 - ? */ Token.Unknown,
  /*  64 - @ */ Token.At,
  /*  65 - A */ Token.Identifier,
  /*  66 - B */ Token.Identifier,
  /*  67 - C */ Token.Identifier,
  /*  68 - D */ Token.Identifier,
  /*  69 - E */ Token.Identifier,
  /*  70 - F */ Token.Identifier,
  /*  71 - G */ Token.Identifier,
  /*  72 - H */ Token.Identifier,
  /*  73 - I */ Token.Identifier,
  /*  74 - J */ Token.Identifier,
  /*  75 - K */ Token.Identifier,
  /*  76 - L */ Token.Identifier,
  /*  77 - M */ Token.Identifier,
  /*  78 - N */ Token.Identifier,
  /*  79 - O */ Token.Identifier,
  /*  80 - P */ Token.Identifier,
  /*  81 - Q */ Token.Identifier,
  /*  82 - R */ Token.Identifier,
  /*  83 - S */ Token.Identifier,
  /*  84 - T */ Token.Identifier,
  /*  85 - U */ Token.Identifier,
  /*  86 - V */ Token.Identifier,
  /*  87 - W */ Token.Identifier,
  /*  88 - X */ Token.Identifier,
  /*  89 - Y */ Token.Identifier,
  /*  90 - Z */ Token.Identifier,
  /*  91 - [ */ Token.Unknown,
  /*  92 - \ */ Token.Unknown,
  /*  93 - ] */ Token.Unknown,
  /*  94 - ^ */ Token.Unknown,
  /*  95 - _ */ Token.Unknown,
  /*  96 - ` */ Token.Unknown,
  /*  97 - a */ Token.IdentifierOrKeyword,
  /*  98 - b */ Token.IdentifierOrKeyword,
  /*  99 - c */ Token.IdentifierOrKeyword,
  /* 100 - d */ Token.IdentifierOrKeyword,
  /* 101 - e */ Token.IdentifierOrKeyword,
  /* 102 - f */ Token.IdentifierOrKeyword,
  /* 103 - g */ Token.IdentifierOrKeyword,
  /* 104 - h */ Token.Identifier,
  /* 105 - i */ Token.Unknown,
  /* 106 - j */ Token.Unknown,
  /* 107 - k */ Token.Unknown,
  /* 108 - l */ Token.Unknown,
  /* 109 - m */ Token.Unknown,
  /* 110 - n */ Token.Unknown,
  /* 111 - o */ Token.Unknown,
  /* 112 - p */ Token.Unknown,
  /* 113 - q */ Token.Unknown,
  /* 114 - r */ Token.Unknown,
  /* 115 - s */ Token.Unknown,
  /* 116 - t */ Token.Unknown,
  /* 117 - u */ Token.Unknown,
  /* 118 - v */ Token.Unknown,
  /* 119 - w */ Token.Unknown,
  /* 120 - x */ Token.Identifier,
  /* 121 - y */ Token.Unknown,
  /* 122 - z */ Token.Unknown,
  /* 123 - { */ Token.Unknown,
  /* 124 - | */ Token.Unknown,
  /* 125 - } */ Token.Unknown,
  /* 126 - ~ */ Token.Unknown,
]
