import { TokenFlags } from "../tokens";

// prettier-ignore
export const firstChar = [
  /*   0 -   */ TokenFlags.Unknown,
  /*   1 -   */ TokenFlags.Unknown,
  /*   2 -   */ TokenFlags.Unknown,
  /*   3 -   */ TokenFlags.Unknown,
  /*   4 -   */ TokenFlags.Unknown,
  /*   5 -   */ TokenFlags.Unknown,
  /*   6 -   */ TokenFlags.Unknown,
  /*   7 -   */ TokenFlags.Unknown,
  /*   8 -   */ TokenFlags.Unknown,
  /*   9 -   */ TokenFlags.Unknown,
  /*  10 -   */ TokenFlags.Unknown,
  /*  11 -   */ TokenFlags.Unknown,
  /*  12 -   */ TokenFlags.Unknown,
  /*  13 -   */ TokenFlags.Unknown,
  /*  14 -   */ TokenFlags.Unknown,
  /*  15 -   */ TokenFlags.Unknown,
  /*  16 -   */ TokenFlags.Unknown,
  /*  17 -   */ TokenFlags.Unknown,
  /*  18 -   */ TokenFlags.Unknown,
  /*  19 -   */ TokenFlags.Unknown,
  /*  20 -   */ TokenFlags.Unknown,
  /*  21 -   */ TokenFlags.Unknown,
  /*  22 -   */ TokenFlags.Unknown,
  /*  23 -   */ TokenFlags.Unknown,
  /*  24 -   */ TokenFlags.Unknown,
  /*  25 -   */ TokenFlags.Unknown,
  /*  26 -   */ TokenFlags.Unknown,
  /*  27 -   */ TokenFlags.Unknown,
  /*  28 -   */ TokenFlags.Unknown,
  /*  29 -   */ TokenFlags.Unknown,
  /*  30 -   */ TokenFlags.Unknown,
  /*  31 -   */ TokenFlags.Unknown,
  /*  32 -   */ TokenFlags.Unknown,
  /*  33 - ! */ TokenFlags.Unknown, // FIXME,
  /*  34 - " */ TokenFlags.StringLiteral,
  /*  35 - # */ TokenFlags.Unknown,
  /*  36 - $ */ TokenFlags.Identifier,
  /*  37 - % */ TokenFlags.Unknown,
  /*  38 - & */ TokenFlags.Unknown,
  /*  39 - ' */ TokenFlags.StringLiteral,
  /*  40 - ( */ TokenFlags.OpenParen,
  /*  41 - ) */ TokenFlags.CloseParen,
  /*  42 - * */ TokenFlags.Unknown,
  /*  43 - + */ TokenFlags.Unknown,
  /*  44 - , */ TokenFlags.Comma,
  /*  45 - - */ TokenFlags.Unknown,
  /*  46 - . */ TokenFlags.Unknown,
  /*  47 - / */ TokenFlags.Unknown,
  /*  48 - 0 */ TokenFlags.NumericLiteral,
  /*  49 - 1 */ TokenFlags.NumericLiteral,
  /*  50 - 2 */ TokenFlags.NumericLiteral,
  /*  51 - 3 */ TokenFlags.NumericLiteral,
  /*  52 - 4 */ TokenFlags.NumericLiteral,
  /*  53 - 5 */ TokenFlags.NumericLiteral,
  /*  54 - 6 */ TokenFlags.NumericLiteral,
  /*  55 - 7 */ TokenFlags.NumericLiteral,
  /*  56 - 8 */ TokenFlags.NumericLiteral,
  /*  57 - 9 */ TokenFlags.NumericLiteral,
  /*  58 - : */ TokenFlags.Colon,
  /*  59 - ; */ TokenFlags.SemiColon,
  /*  60 - < */ TokenFlags.Unknown,
  /*  61 - = */ TokenFlags.Equals,
  /*  62 - > */ TokenFlags.Unknown,
  /*  63 - ? */ TokenFlags.Unknown,
  /*  64 - @ */ TokenFlags.At,
  /*  65 - A */ TokenFlags.Identifier,
  /*  66 - B */ TokenFlags.Identifier,
  /*  67 - C */ TokenFlags.Identifier,
  /*  68 - D */ TokenFlags.Identifier,
  /*  69 - E */ TokenFlags.Identifier,
  /*  70 - F */ TokenFlags.Identifier,
  /*  71 - G */ TokenFlags.Identifier,
  /*  72 - H */ TokenFlags.Identifier,
  /*  73 - I */ TokenFlags.Identifier,
  /*  74 - J */ TokenFlags.Identifier,
  /*  75 - K */ TokenFlags.Identifier,
  /*  76 - L */ TokenFlags.Identifier,
  /*  77 - M */ TokenFlags.Identifier,
  /*  78 - N */ TokenFlags.Identifier,
  /*  79 - O */ TokenFlags.Identifier,
  /*  80 - P */ TokenFlags.Identifier,
  /*  81 - Q */ TokenFlags.Identifier,
  /*  82 - R */ TokenFlags.Identifier,
  /*  83 - S */ TokenFlags.Identifier,
  /*  84 - T */ TokenFlags.Identifier,
  /*  85 - U */ TokenFlags.Identifier,
  /*  86 - V */ TokenFlags.Identifier,
  /*  87 - W */ TokenFlags.Identifier,
  /*  88 - X */ TokenFlags.Identifier,
  /*  89 - Y */ TokenFlags.Identifier,
  /*  90 - Z */ TokenFlags.Identifier,
  /*  91 - [ */ TokenFlags.Unknown,
  /*  92 - \ */ TokenFlags.Unknown,
  /*  93 - ] */ TokenFlags.Unknown,
  /*  94 - ^ */ TokenFlags.Unknown,
  /*  95 - _ */ TokenFlags.Unknown,
  /*  96 - ` */ TokenFlags.Unknown,
  /*  97 - a */ TokenFlags.IdentifierOrKeyword,
  /*  98 - b */ TokenFlags.IdentifierOrKeyword,
  /*  99 - c */ TokenFlags.IdentifierOrKeyword,
  /* 100 - d */ TokenFlags.IdentifierOrKeyword,
  /* 101 - e */ TokenFlags.IdentifierOrKeyword,
  /* 102 - f */ TokenFlags.IdentifierOrKeyword,
  /* 103 - g */ TokenFlags.IdentifierOrKeyword,
  /* 104 - h */ TokenFlags.Identifier,
  /* 105 - i */ TokenFlags.Unknown,
  /* 106 - j */ TokenFlags.Unknown,
  /* 107 - k */ TokenFlags.Unknown,
  /* 108 - l */ TokenFlags.Unknown,
  /* 109 - m */ TokenFlags.Unknown,
  /* 110 - n */ TokenFlags.Unknown,
  /* 111 - o */ TokenFlags.Unknown,
  /* 112 - p */ TokenFlags.Unknown,
  /* 113 - q */ TokenFlags.Unknown,
  /* 114 - r */ TokenFlags.Unknown,
  /* 115 - s */ TokenFlags.Unknown,
  /* 116 - t */ TokenFlags.Unknown,
  /* 117 - u */ TokenFlags.Unknown,
  /* 118 - v */ TokenFlags.Unknown,
  /* 119 - w */ TokenFlags.Unknown,
  /* 120 - x */ TokenFlags.Identifier,
  /* 121 - y */ TokenFlags.Unknown,
  /* 122 - z */ TokenFlags.Unknown,
  /* 123 - { */ TokenFlags.Unknown,
  /* 124 - | */ TokenFlags.Unknown,
  /* 125 - } */ TokenFlags.Unknown,
  /* 126 - ~ */ TokenFlags.Unknown,
]
